"""SME-complete station graph and extra curated URLs.

Imported by compile_catalog.py. Every station has do / parallel / skim / project.
"""

from __future__ import annotations


def C(
    title: str,
    url: str,
    *,
    kind: str,
    provider: str,
    level: str,
    pedagogy: list[str],
    branches: list[str],
    evidence: str,
    featured: bool = True,
    sitting: str | None = None,
    scores: dict | None = None,
) -> dict:
    rec = {
        "title": title,
        "url": url,
        "kind": kind,
        "provider": provider,
        "level": level,
        "pedagogy": pedagogy,
        "branches": branches,
        "evidence": evidence,
        "featured": featured,
    }
    if sitting:
        rec["sitting"] = sitting
    if scores:
        rec["scores"] = scores
    return rec


def S(
    id: str,
    title: str,
    stage: int,
    rail: str,
    branch: str,
    prereqs: list[str],
    why: str,
    do: list[str],
    parallel: list[str],
    skim: list[str],
    project: list[str],
) -> dict:
    return {
        "id": id,
        "title": title,
        "stage": stage,
        "rail": rail,
        "branch": branch,
        "prereqs": prereqs,
        "why": why,
        "do": do,
        "parallel": parallel,
        "skim": skim,
        "project": project,
    }


CURATED_EXTRA = [
    C("MIT 6.042J Mathematics for Computer Science", "https://ocw.mit.edu/courses/6-042j-mathematics-for-computer-science-fall-2010/", kind="course", provider="mit-ocw", level="intro", pedagogy=["proofs", "assignments"], branches=["theory"], evidence="Proofs, graphs, counting. The discrete-math on-ramp if later theory feels opaque.", sitting="~3 h (lecture + recitation)", scores={"intuition": 3, "exercises": 5, "stack": 3, "depth": 5}),
    C("fast.ai Computational Linear Algebra", "https://github.com/fastai/numerical-linear-algebra", kind="course", provider="fast.ai", level="intermediate", pedagogy=["assignments", "from-scratch"], branches=["linear-algebra"], evidence="Numerical LA in notebooks. The practice project after Strang.", sitting="~3 h (one notebook)", scores={"intuition": 4, "exercises": 5, "stack": 5, "depth": 4}),
    C("sklearn clustering guide", "https://scikit-learn.org/stable/modules/clustering.html", kind="article", provider="sklearn", level="intro", pedagogy=["assignments"], branches=["classical-ml"], evidence="Working clustering API after ISL unsupervised chapters.", sitting="~1 h", scores={"intuition": 3, "exercises": 4, "stack": 5, "depth": 3}),
    C("Gradient Boosting Explained (explained.ai)", "https://explained.ai/gradient-boosting/index.html", kind="article", provider="explained-ai", level="intermediate", pedagogy=["visual"], branches=["classical-ml"], evidence="Best written GBM intuition. Pair with XGBoost docs.", sitting="~1 h", scores={"intuition": 5, "exercises": 2, "stack": 4, "depth": 4}),
    C("XGBoost model tutorial", "https://xgboost.readthedocs.io/en/stable/tutorials/model.html", kind="article", provider="xgboost", level="intermediate", pedagogy=["assignments"], branches=["classical-ml"], evidence="The library you will actually ship for tabular.", sitting="~1 h", scores={"intuition": 3, "exercises": 4, "stack": 5, "depth": 3}),
    C("Rules of Machine Learning (Google)", "https://developers.google.com/machine-learning/guides/rules-of-ml", kind="article", provider="google", level="intermediate", pedagogy=["production"], branches=["eval", "mlsys"], evidence="Leakage, metrics, and iteration order from production ML.", sitting="~1 h", scores={"intuition": 4, "exercises": 3, "stack": 5, "depth": 4}),
    C("MLU-Explain", "https://mlu-explain.github.io/", kind="article", provider="amazon", level="intro", pedagogy=["visual"], branches=["eval", "classical-ml"], evidence="Interactive bias-variance, ROC, calibration. Eval station visual rail.", sitting="~1 h", scores={"intuition": 5, "exercises": 2, "stack": 4, "depth": 3}),
    C("Understanding LSTM Networks (Colah)", "https://colah.github.io/posts/2015-08-Understanding-LSTMs/", kind="article", provider="colah", level="intermediate", pedagogy=["visual"], branches=["nlp", "deep-learning"], evidence="The LSTM diagram everyone actually learned from.", sitting="~1 h", scores={"intuition": 5, "exercises": 1, "stack": 3, "depth": 4}),
    C("SimCLR", "https://arxiv.org/abs/2002.05709", kind="paper", provider="arxiv", level="advanced", pedagogy=["proofs"], branches=["computer-vision", "deep-learning"], evidence="Contrastive SSL that still explains modern vision pretraining.", sitting="~2 h (skim)", scores={"intuition": 3, "exercises": 1, "stack": 4, "depth": 5}),
    C("DINOv2", "https://arxiv.org/abs/2304.07193", kind="paper", provider="arxiv", level="advanced", pedagogy=["proofs"], branches=["computer-vision"], evidence="2023 frozen-feature vision. Current SSL interest."),
    C("Lilian Weng: Self-Supervised Learning", "https://lilianweng.github.io/posts/2019-11-10-self-supervised/", kind="article", provider="lilianweng", level="intermediate", pedagogy=["visual"], branches=["deep-learning"], evidence="Survey that still maps the SSL zoo.", sitting="~1 h", scores={"intuition": 5, "exercises": 1, "stack": 4, "depth": 4}),
    C("Hugging Face Diffusion Course", "https://huggingface.co/learn/diffusion-course", kind="course", provider="huggingface", level="intermediate", pedagogy=["assignments"], branches=["diffusion", "generative"], evidence="Hands-on DDPM → Stable Diffusion. The gen-vision practice course.", sitting="~3 h (unit 1)", scores={"intuition": 4, "exercises": 5, "stack": 5, "depth": 3}),
    C("DDPM", "https://arxiv.org/abs/2006.11239", kind="paper", provider="arxiv", level="advanced", pedagogy=["proofs"], branches=["diffusion"], evidence="Denoising diffusion probabilistic models. Read after the HF course."),
    C("VAE (Kingma & Welling)", "https://arxiv.org/abs/1312.6114", kind="paper", provider="arxiv", level="advanced", pedagogy=["proofs"], branches=["generative"], evidence="The generative-model ancestor. Still the right first paper."),
    C("GAN (Goodfellow)", "https://arxiv.org/abs/1406.2661", kind="paper", provider="arxiv", level="advanced", pedagogy=["proofs"], branches=["generative"], evidence="Historical; know it, then spend time on diffusion."),
    C("Lilian Weng: Diffusion Models", "https://lilianweng.github.io/posts/2021-07-11-diffusion-models/", kind="article", provider="lilianweng", level="intermediate", pedagogy=["visual"], branches=["diffusion"], evidence="Best single diffusion explainer before the papers.", sitting="~1 h", scores={"intuition": 5, "exercises": 1, "stack": 4, "depth": 4}),
    C("Stanford CS224W Machine Learning with Graphs", "https://web.stanford.edu/class/cs224w/", kind="course", provider="stanford", level="intermediate", pedagogy=["assignments"], branches=["graphs"], evidence="Canonical GNN course. Assignments are the point.", sitting="~4 h (colab 1)", scores={"intuition": 3, "exercises": 5, "stack": 4, "depth": 4}),
    C("Geometric Deep Learning", "https://geometricdeeplearning.com/", kind="course", provider="bronstein", level="advanced", pedagogy=["proofs"], branches=["graphs"], evidence="Bronstein et al. The theory of graphs, grids, groups, geodesics."),
    C("A Gentle Introduction to GNNs (Distill)", "https://distill.pub/2021/gnn-intro/", kind="article", provider="distill", level="intro", pedagogy=["visual"], branches=["graphs"], evidence="Visual GNN on-ramp before CS224W.", sitting="~1 h", scores={"intuition": 5, "exercises": 1, "stack": 3, "depth": 3}),
    C("Hugging Face Audio Course", "https://huggingface.co/learn/audio-course", kind="course", provider="huggingface", level="intermediate", pedagogy=["assignments"], branches=["speech"], evidence="ASR, TTS, classification in Transformers. The speech practice rail.", sitting="~3 h (chapter 1)", scores={"intuition": 4, "exercises": 5, "stack": 5, "depth": 3}),
    C("Robust Speech Recognition via Large-Scale Weak Supervision (Whisper)", "https://arxiv.org/abs/2212.04356", kind="paper", provider="arxiv", level="advanced", pedagogy=["proofs"], branches=["speech"], evidence="Whisper. Current default ASR baseline.", sitting="~2 h (skim)", scores={"intuition": 3, "exercises": 1, "stack": 5, "depth": 4}),
    C("Stanford HELM", "https://crfm.stanford.edu/helm/", kind="article", provider="stanford", level="advanced", pedagogy=["eval"], branches=["eval", "nlp"], evidence="Holistic LLM evaluation. Eval station, not a vibes leaderboard.", sitting="~2 h (skim leaderboard + one scenario)", scores={"intuition": 3, "exercises": 2, "stack": 4, "depth": 4}),
    C("LMSYS Chatbot Arena", "https://lmsys.org/blog/2023-05-03-arena/", kind="article", provider="lmsys", level="intermediate", pedagogy=["eval"], branches=["eval", "generative"], evidence="Human-preference eval at scale. Know its biases."),
    C("EleutherAI lm-evaluation-harness", "https://github.com/EleutherAI/lm-evaluation-harness", kind="repo", provider="eleutherai", level="intermediate", pedagogy=["assignments"], branches=["eval", "nlp"], evidence="The harness you actually run. Project for LLM eval.", sitting="~3 h (run one task)", scores={"intuition": 2, "exercises": 5, "stack": 5, "depth": 4}),
    C("ReAct", "https://arxiv.org/abs/2210.03629", kind="paper", provider="arxiv", level="advanced", pedagogy=["proofs"], branches=["agents"], evidence="Reason + act. The paper under most agent stacks."),
    C("Lilian Weng: LLM Powered Autonomous Agents", "https://lilianweng.github.io/posts/2023-06-23-agent/", kind="article", provider="lilianweng", level="intermediate", pedagogy=["visual"], branches=["agents"], evidence="Memory, tools, planning. Best agent survey.", sitting="~1 h", scores={"intuition": 5, "exercises": 1, "stack": 4, "depth": 4}),
    C("CLIP", "https://arxiv.org/abs/2103.00020", kind="paper", provider="arxiv", level="advanced", pedagogy=["proofs"], branches=["multimodal", "computer-vision"], evidence="Contrastive image-text. Backbone of multimodal 2021–now.", sitting="~2 h (skim)", scores={"intuition": 4, "exercises": 1, "stack": 5, "depth": 5}),
    C("LLaVA", "https://arxiv.org/abs/2304.08485", kind="paper", provider="arxiv", level="advanced", pedagogy=["proofs"], branches=["multimodal"], evidence="Visual instruction tuning. Current VLM recipe.", sitting="~2 h (skim)", scores={"intuition": 3, "exercises": 1, "stack": 5, "depth": 4}),
    C("Hugging Face Computer Vision Course", "https://huggingface.co/learn/computer-vision-course", kind="course", provider="huggingface", level="intermediate", pedagogy=["assignments"], branches=["computer-vision"], evidence="Modern CV tooling parallel to CS231n."),
    C("Bandit Algorithms (Lattimore & Szepesvári)", "https://tor-lattimore.com/downloads/book/book.pdf", kind="book", provider="banditalgs", level="advanced", pedagogy=["proofs"], branches=["bandits", "rl"], evidence="The bandit book (author PDF). Do selected chapters, not all 32."),
    C("Decision Transformer", "https://arxiv.org/abs/2106.01345", kind="paper", provider="arxiv", level="advanced", pedagogy=["proofs"], branches=["imitation", "rl"], evidence="Offline RL as sequence modeling. Current crossover with LLMs."),
    C("Multi-Agent Reinforcement Learning (Albrecht, Christianos, Schäfer)", "https://www.marl-book.com/", kind="book", provider="marl-book", level="advanced", pedagogy=["proofs"], branches=["marl", "rl"], evidence="2024 MARL textbook. The multi-agent station."),
    C("World Models (Ha & Schmidhuber)", "https://worldmodels.github.io/", kind="article", provider="ha", level="intermediate", pedagogy=["visual", "from-scratch"], branches=["world-models", "rl"], evidence="VAE+MDN-RNN+controller. Fun and historically load-bearing."),
    C("DreamerV3", "https://arxiv.org/abs/2301.04104", kind="paper", provider="arxiv", level="advanced", pedagogy=["proofs"], branches=["world-models", "rl"], evidence="Current world-model RL that actually works across domains."),
    C("MIT Introduction to Data-Centric AI", "https://dcai.csail.mit.edu/", kind="course", provider="mit", level="intermediate", pedagogy=["assignments"], branches=["data-centric", "eval"], evidence="Data quality over model shopping. T5 theory rail."),
    C("DeepLearning.AI Data-Centric AI", "https://www.deeplearning.ai/short-courses/data-centric-ai/", kind="course", provider="deeplearning.ai", level="intro", pedagogy=["assignments"], branches=["data-centric"], evidence="Short Ng course. Parallel to MIT DCAI."),
    C("CUDA Mode lectures", "https://github.com/cuda-mode/lectures", kind="lecture-series", provider="cuda-mode", level="advanced", pedagogy=["from-scratch"], branches=["compilers", "mlsys"], evidence="Kernels, profiling, FlashAttention-era GPU programming."),
    C("FlashAttention", "https://arxiv.org/abs/2205.14135", kind="paper", provider="arxiv", level="advanced", pedagogy=["proofs"], branches=["compilers", "nlp"], evidence="IO-aware attention. Why modern transformers are fast."),
    C("The Algorithmic Foundations of Differential Privacy (Dwork & Roth)", "https://www.cis.upenn.edu/~aaroth/Papers/privacybook.pdf", kind="book", provider="upenn", level="advanced", pedagogy=["proofs"], branches=["privacy"], evidence="The DP book. SME privacy, not a vendor checklist."),
    C("Eugene Yan: Evaluation for ML", "https://eugeneyan.com/writing/evals/", kind="article", provider="eugeneyan", level="intermediate", pedagogy=["production"], branches=["eval", "mlsys"], evidence="Practical eval in production. T5 practice companion."),
    C("CS228 Probabilistic Graphical Models notes (Stanford)", "https://ermongroup.github.io/cs228-notes/", kind="course", provider="stanford", level="advanced", pedagogy=["proofs"], branches=["pgm", "probability"], evidence="Ermon group notes. Parallel to Koller Coursera."),
    C("Google Recommendation Systems crash course", "https://developers.google.com/machine-learning/recommendation", kind="course", provider="google", level="intro", pedagogy=["assignments"], branches=["recommenders"], evidence="Candidate generation → ranking. Clear production shape."),
    C("Recommender Systems Specialization (U of Minnesota)", "https://www.coursera.org/specializations/recommender-systems", kind="course", provider="coursera", level="intermediate", pedagogy=["assignments"], branches=["recommenders"], evidence="Coursera recsys with assignments. Employer access."),
    C("Forecasting: Principles and Practice (Hyndman & Athanasopoulos)", "https://otexts.com/fpp3/", kind="book", provider="hyndman", level="intermediate", pedagogy=["assignments"], branches=["timeseries"], evidence="The forecasting book. Statistical TS before patching a transformer on it."),
    C("sktime documentation", "https://www.sktime.net/en/stable/", kind="article", provider="sktime", level="intermediate", pedagogy=["assignments"], branches=["timeseries"], evidence="Unified Python TS API. The project library."),
    C("Underactuated Robotics (Tedrake)", "https://underactuated.csail.mit.edu/", kind="course", provider="mit", level="advanced", pedagogy=["proofs", "assignments"], branches=["robotics"], evidence="Control + learning. Best robotics theory course that talks to ML."),
    C("Robotic Manipulation (Tedrake)", "https://manipulation.csail.mit.edu/", kind="course", provider="mit", level="advanced", pedagogy=["assignments"], branches=["robotics"], evidence="Perception to grasping. Practice rail with Drake."),
    C("LeRobot", "https://github.com/huggingface/lerobot", kind="repo", provider="huggingface", level="intermediate", pedagogy=["assignments"], branches=["robotics"], evidence="Open real-robot + sim stack. Current embodied-AI interest."),
    C("Modern Robotics Specialization (Northwestern)", "https://www.coursera.org/specializations/modernrobotics", kind="course", provider="coursera", level="intermediate", pedagogy=["assignments"], branches=["robotics"], evidence="Lie groups, kinematics. Employer Coursera."),
    C("Physics-informed neural networks (Raissi)", "https://arxiv.org/abs/1711.10561", kind="paper", provider="arxiv", level="advanced", pedagogy=["proofs"], branches=["scientific-ml"], evidence="PINNs. The scientific-ML starter paper."),
    C("Neural Ordinary Differential Equations", "https://arxiv.org/abs/1806.07366", kind="paper", provider="arxiv", level="advanced", pedagogy=["proofs"], branches=["scientific-ml", "deep-learning"], evidence="Continuous-depth nets. Still a live research object."),
    C("Neel Nanda: Getting started with mechanistic interpretability", "https://www.neelnanda.io/mechanistic-interpretability/getting-started", kind="article", provider="neelnanda", level="advanced", pedagogy=["from-scratch"], branches=["interpretability"], evidence="The actual on-ramp used by interp people in 2024–26."),
    C("TransformerLens", "https://transformerlensorg.github.io/TransformerLens/", kind="article", provider="transformerlens", level="advanced", pedagogy=["assignments"], branches=["interpretability"], evidence="The library for mech interp projects."),
    C("Zoom In: An Introduction to Circuits (Distill)", "https://distill.pub/2020/circuits/", kind="article", provider="distill", level="advanced", pedagogy=["visual"], branches=["interpretability"], evidence="Vision circuits. Historical and still the visual intro."),
    C("ARENA", "https://www.arena.education/", kind="course", provider="arena", level="advanced", pedagogy=["assignments"], branches=["interpretability", "alignment"], evidence="Alignment + interp bootcamp. Heavy; SME-year."),
    C("InstructGPT", "https://arxiv.org/abs/2203.02155", kind="paper", provider="arxiv", level="advanced", pedagogy=["proofs"], branches=["alignment", "generative"], evidence="RLHF as shipped. Read before DPO folklore."),
    C("Direct Preference Optimization", "https://arxiv.org/abs/2305.18290", kind="paper", provider="arxiv", level="advanced", pedagogy=["proofs"], branches=["alignment"], evidence="DPO. Current default alignment algorithm to understand."),
    C("Constitutional AI", "https://arxiv.org/abs/2212.08073", kind="paper", provider="arxiv", level="advanced", pedagogy=["proofs"], branches=["alignment"], evidence="RLAIF / principles. Anthropic line."),
    C("AI Safety Fundamentals (BlueDot)", "https://course.aisafetyfundamentals.com/", kind="course", provider="bluedot", level="intro", pedagogy=["visual"], branches=["alignment"], evidence="Survey course. Parallel, not a substitute for the papers."),
    C("Hugging Face RLHF blog", "https://huggingface.co/blog/rlhf", kind="article", provider="huggingface", level="intermediate", pedagogy=["visual"], branches=["alignment"], evidence="Practical RLHF stack diagram."),
    C("NeRF", "https://arxiv.org/abs/2003.08934", kind="paper", provider="arxiv", level="advanced", pedagogy=["proofs"], branches=["3d-vision", "computer-vision"], evidence="Neural radiance fields. 3D vision exploded here."),
    C("3D Gaussian Splatting", "https://repo-sam.inria.fr/fungraph/3d-gaussian-splatting/", kind="article", provider="inria", level="advanced", pedagogy=["visual"], branches=["3d-vision"], evidence="2023–26 realtime 3D. Current interest vs NeRF."),
    C("NeRF project page (Mildenhall / Tancik)", "https://www.matthewtancik.com/nerf", kind="article", provider="tancik", level="advanced", pedagogy=["visual"], branches=["3d-vision"], evidence="Results + data. Pair with the paper."),
    C("Fairness and Machine Learning (Barocas, Hardt, Narayanan)", "https://fairmlbook.org/", kind="book", provider="fairmlbook", level="intermediate", pedagogy=["proofs"], branches=["fairness"], evidence="The fairness textbook. Not optional for SME."),
    C("Chain-of-Thought Prompting", "https://arxiv.org/abs/2201.11903", kind="paper", provider="arxiv", level="intermediate", pedagogy=["proofs"], branches=["nlp", "generative"], evidence="CoT. The test-time compute ancestor."),
    C("Let's Verify Step by Step", "https://arxiv.org/abs/2305.20050", kind="paper", provider="arxiv", level="advanced", pedagogy=["proofs"], branches=["alignment", "eval"], evidence="Process vs outcome reward. Reasoning-model lineage."),
    C("DeepSeek-R1", "https://arxiv.org/abs/2501.12948", kind="paper", provider="arxiv", level="advanced", pedagogy=["proofs"], branches=["generative", "alignment"], evidence="2025 reasoning-model paper. Latest interest, not a first course."),
    C("Mamba: Linear-Time Sequence Modeling with Selective State Spaces", "https://arxiv.org/abs/2312.00752", kind="paper", provider="arxiv", level="advanced", pedagogy=["proofs"], branches=["ssm", "nlp"], evidence="Selective SSMs. The architecture alternative to attention.", sitting="~2 h (skim)", scores={"intuition": 3, "exercises": 1, "stack": 4, "depth": 5}),
    C("Efficiently Modeling Long Sequences with Structured State Spaces (S4)", "https://arxiv.org/abs/2111.00396", kind="paper", provider="arxiv", level="advanced", pedagogy=["proofs"], branches=["ssm"], evidence="S4. Read before Mamba.", sitting="~2 h (skim)", scores={"intuition": 3, "exercises": 1, "stack": 3, "depth": 5}),
    C("state-spaces/mamba", "https://github.com/state-spaces/mamba", kind="repo", provider="github", level="advanced", pedagogy=["from-scratch"], branches=["ssm"], evidence="Reference implementation. The SSM project."),
    C("LoRA", "https://arxiv.org/abs/2106.09685", kind="paper", provider="arxiv", level="intermediate", pedagogy=["proofs"], branches=["generative", "nlp"], evidence="Low-rank adaptation. How people actually fine-tune."),
    C("Hugging Face PEFT", "https://huggingface.co/docs/peft/index", kind="article", provider="huggingface", level="intermediate", pedagogy=["assignments"], branches=["generative"], evidence="LoRA/QLoRA in practice."),
    C("Switch Transformers", "https://arxiv.org/abs/2101.03961", kind="paper", provider="arxiv", level="advanced", pedagogy=["proofs"], branches=["nlp", "generative"], evidence="MoE at scale. Mixtral's ancestor."),
    C("Mixtral of Experts", "https://arxiv.org/abs/2401.04088", kind="paper", provider="arxiv", level="advanced", pedagogy=["proofs"], branches=["generative"], evidence="Sparse MoE that shipped. Current systems interest."),
    C("Stanford CS336 Language Modeling from Scratch", "https://stanford-cs336.github.io/spring2025/", kind="course", provider="stanford", level="advanced", pedagogy=["assignments", "from-scratch"], branches=["nlp", "generative"], evidence="2025 data → tokenizer → train → eval. Latest university LLM course.", sitting="~4 h (assignment 1)", scores={"intuition": 3, "exercises": 5, "stack": 5, "depth": 5}),
    C("Stanford CS25 Transformers United", "https://web.stanford.edu/class/cs25/", kind="course", provider="stanford", level="intermediate", pedagogy=["visual"], branches=["nlp", "generative"], evidence="Guest-lecture survey of transformer applications."),
    C("Evaluating Large Language Models (Stanford CS324 notes)", "https://stanford-cs324.github.io/winter2022/", kind="course", provider="stanford", level="intermediate", pedagogy=["visual"], branches=["nlp", "eval"], evidence="Early LLM seminar. Skim; HELM is the eval object."),
    C("Brady Neal Causal Inference", "https://www.bradyneal.com/causal-inference-course", kind="course", provider="neal", level="intro", pedagogy=["visual"], branches=["causal"], evidence="Friendlier than Pearl first. Parallel to Facure."),
    C("Causal Inference: What If (Hernán & Robins)", "https://www.hsph.harvard.edu/miguel-hernan/causal-inference-book/", kind="book", provider="harvard", level="advanced", pedagogy=["proofs"], branches=["causal"], evidence="Epidemiology-grade causal inference. SME depth."),
    C("Chip Huyen Machine Learning Systems Design", "https://github.com/chiphuyen/machine-learning-systems-design", kind="book", provider="huyenchip", level="intermediate", pedagogy=["production"], branches=["mlsys"], evidence="Interview + systems notes. Use with the O'Reilly book."),
    C("Evaluating LLMs is a minefield (Anthropic / related eval writing)", "https://www.anthropic.com/research", kind="article", provider="anthropic", level="advanced", pedagogy=["visual"], branches=["alignment", "eval"], evidence="Primary lab research stream. Skim latest, don't treat as a course."),
    C("Segment Anything", "https://arxiv.org/abs/2304.02643", kind="paper", provider="arxiv", level="advanced", pedagogy=["proofs"], branches=["computer-vision"], evidence="SAM. Foundation model for segmentation."),
    C("AlphaFold 2 (Nature)", "https://www.nature.com/articles/s41586-021-03819-2", kind="paper", provider="nature", level="advanced", pedagogy=["proofs"], branches=["scientific-ml"], evidence="Scientific ML that changed a field. Skim architecture, don't skip the result."),
    C("The Stack (software LLMs data)", "https://arxiv.org/abs/2211.15533", kind="paper", provider="arxiv", level="intermediate", pedagogy=["proofs"], branches=["code-llm"], evidence="Code-LLM pretraining data. Know the data, not only Copilot demos.", sitting="~1 h (skim)", scores={"intuition": 3, "exercises": 1, "stack": 4, "depth": 4}),
    C("Evaluating Large Language Models Trained on Code (Codex)", "https://arxiv.org/abs/2107.03374", kind="paper", provider="arxiv", level="advanced", pedagogy=["proofs"], branches=["code-llm"], evidence="Codex. Ancestor of code models.", sitting="~2 h (skim)", scores={"intuition": 3, "exercises": 1, "stack": 4, "depth": 5}),
    C("Communication-Efficient Learning of Deep Networks from Decentralized Data", "https://arxiv.org/abs/1602.05629", kind="paper", provider="arxiv", level="advanced", pedagogy=["proofs"], branches=["privacy"], evidence="FedAvg. Federated learning starter."),
    C("AutoML: Methods, Systems, Challenges (Hutter et al.)", "https://www.automl.org/book/", kind="book", provider="automl", level="advanced", pedagogy=["proofs"], branches=["classical-ml"], evidence="NAS and HPO. Branch, not spine."),
    C("A Survey of Continual Learning", "https://arxiv.org/abs/2302.00487", kind="paper", provider="arxiv", level="advanced", pedagogy=["visual"], branches=["deep-learning"], evidence="Forgetting, replay, regularization. Know the problem exists."),
    C("Knowledge Graphs (Hogan et al. survey)", "https://arxiv.org/abs/2003.02320", kind="paper", provider="arxiv", level="advanced", pedagogy=["visual"], branches=["nlp"], evidence="KG survey if you go neuro-symbolic / RAG-with-structure."),
    C("PyTorch 2.0 / torch.compile tutorial", "https://pytorch.org/tutorials/intermediate/torch_compile_tutorial.html", kind="article", provider="pytorch", level="intermediate", pedagogy=["assignments"], branches=["compilers"], evidence="Compiler stack you will hit in 2024–26 training."),
    C("OpenAI Whisper GitHub", "https://github.com/openai/whisper", kind="repo", provider="openai", level="intermediate", pedagogy=["assignments"], branches=["speech"], evidence="Run ASR on your own audio. Speech project."),
    C("nanoGPT", "https://github.com/karpathy/nanoGPT", kind="project", provider="karpathy", level="intermediate", pedagogy=["from-scratch"], branches=["code-llm", "nlp"], evidence="Also the code-LLM project: train on a code corpus."),
    C("Gymnasium", "https://gymnasium.farama.org/", kind="article", provider="farama", level="intermediate", pedagogy=["assignments"], branches=["rl"], evidence="Env API. Bandits/RL projects live here."),
    C("sklearn user guide: preprocessing", "https://scikit-learn.org/stable/modules/preprocessing.html", kind="article", provider="sklearn", level="intro", pedagogy=["assignments"], branches=["eval"], evidence="Pipelines and leakage surfaces. Eval/data station."),
    C("Boyd Convex Optimization lectures", "https://web.stanford.edu/~boyd/papers/cvx_short_course.html", kind="lecture-series", provider="stanford", level="advanced", pedagogy=["proofs"], branches=["optimization"], evidence="Short course slides next to the book."),
    C("Information Theory (YouTube MacKay lectures index)", "https://www.inference.org.uk/mackay/itila/", kind="book", provider="mackay", level="advanced", pedagogy=["proofs"], branches=["info-theory"], evidence="Book + lecture videos linked from the site. Info-theory Do."),
    C("AIMA exercises / code", "https://github.com/aimacode/aima-python", kind="repo", provider="berkeley", level="intro", pedagogy=["assignments"], branches=["classical-ml"], evidence="Search/planning project code for CS188/AIMA."),
    C("fast.ai part 1 pets notebook (course project home)", "https://course.fast.ai/Lessons/lesson1.html", kind="course", provider="fast.ai", level="intro", pedagogy=["assignments"], branches=["computer-vision"], evidence="Lesson 1 is the CV project seed if CS231n homework is too heavy."),
    C("Kaggle: Playground / competitions hub", "https://www.kaggle.com/competitions", kind="article", provider="kaggle", level="intro", pedagogy=["assignments"], branches=["classical-ml"], evidence="Pick one competition as a station project, not as a lifestyle."),
    C("Stanford CS221 projects", "https://stanford-cs221.github.io/", kind="course", provider="stanford", level="intermediate", pedagogy=["assignments"], branches=["classical-ml"], evidence="Pacman-style and MDP projects. Search station project.", sitting="~4 h (one project)", scores={"intuition": 3, "exercises": 5, "stack": 4, "depth": 4}),
    C("CS231n assignments", "https://cs231n.github.io/assignments/2024/assignment1/", kind="article", provider="stanford", level="intermediate", pedagogy=["assignments"], branches=["computer-vision"], evidence="Numpy → nets. The CV project."),
    C("HF NLP course chapter 7 (seq2seq project)", "https://huggingface.co/learn/nlp-course/chapter7/1", kind="course", provider="huggingface", level="intermediate", pedagogy=["assignments"], branches=["nlp"], evidence="Translation/summarization project after tokenizers."),
    C("GAIA: a benchmark for General AI Assistants", "https://arxiv.org/abs/2311.12983", kind="paper", provider="arxiv", level="advanced", pedagogy=["eval"], branches=["agents", "eval"], evidence="Real assistant tasks, not MMLU. Agent-eval Do list.", sitting="~2 h (skim)", scores={"intuition": 3, "exercises": 2, "stack": 4, "depth": 4}),
    C("SWE-bench", "https://www.swebench.com/", kind="article", provider="swebench", level="advanced", pedagogy=["eval", "assignments"], branches=["agents", "code-llm", "eval"], evidence="Agents on real GitHub issues. The coding-agent eval.", sitting="~2 h (read + one sample)", scores={"intuition": 3, "exercises": 4, "stack": 5, "depth": 4}),
    C("SWE-bench (paper)", "https://arxiv.org/abs/2310.06770", kind="paper", provider="arxiv", level="advanced", pedagogy=["proofs"], branches=["agents", "eval"], evidence="Paper behind SWE-bench."),
    C("τ-bench (tau-bench)", "https://arxiv.org/abs/2406.12045", kind="paper", provider="arxiv", level="advanced", pedagogy=["eval"], branches=["agents", "eval"], evidence="Tool-user agents in domain policies. Current agent-eval interest."),
    C("AgentBench", "https://arxiv.org/abs/2308.03688", kind="paper", provider="arxiv", level="advanced", pedagogy=["eval"], branches=["agents", "eval"], evidence="Multi-environment LLM-agent benchmark."),
    C("Berkeley Function Calling Leaderboard", "https://gorilla.cs.berkeley.edu/leaderboard.html", kind="article", provider="berkeley", level="intermediate", pedagogy=["eval"], branches=["agents", "eval"], evidence="Tool/function-call eval. Parallel to GAIA."),
    C("Toolformer", "https://arxiv.org/abs/2302.04761", kind="paper", provider="arxiv", level="advanced", pedagogy=["proofs"], branches=["agents"], evidence="Self-supervised tool use. Ancestor of function calling."),
    C("Game Theory I (Stanford / UBC on Coursera)", "https://www.coursera.org/learn/game-theory-1", kind="course", provider="coursera", level="intro", pedagogy=["assignments"], branches=["ai"], evidence="Normal-form games, Nash. Classical AI, not MARL yet.", sitting="~3 h (week 1)", scores={"intuition": 4, "exercises": 4, "stack": 3, "depth": 4}),
    C("Mastering the game of Go (AlphaGo)", "https://www.nature.com/articles/nature16961", kind="paper", provider="nature", level="advanced", pedagogy=["proofs"], branches=["ai", "rl"], evidence="Search + learning. Why MCTS is on the AI spine.", sitting="~2 h (skim architecture)", scores={"intuition": 4, "exercises": 1, "stack": 3, "depth": 5}),
    C("Multiagent Systems (Shoham & Leyton-Brown, free book)", "https://www.masfoundations.org/", kind="book", provider="masfoundations", level="advanced", pedagogy=["proofs"], branches=["ai", "marl"], evidence="Game theory + mechanism design for multi-agent AI."),
    C("Knowledge Graphs (Hogan et al.)", "https://arxiv.org/abs/2003.02320", kind="paper", provider="arxiv", level="advanced", pedagogy=["visual"], branches=["ai", "nlp"], evidence="KG survey. Structure for RAG and neuro-symbolic.", sitting="~2 h (skim)", scores={"intuition": 3, "exercises": 1, "stack": 3, "depth": 5}),
    C("Stanford CS520 Knowledge Graphs", "https://web.stanford.edu/class/cs520/", kind="course", provider="stanford", level="intermediate", pedagogy=["assignments"], branches=["ai"], evidence="University KG course. The knowledge-graph station.", sitting="~3 h (one lecture + notes)", scores={"intuition": 3, "exercises": 4, "stack": 3, "depth": 4}),
    C("Coursera Knowledge Graphs (IBM)", "https://www.coursera.org/learn/ibm-knowledge-graphs", kind="course", provider="coursera", level="intro", pedagogy=["assignments"], branches=["ai"], evidence="Employer Coursera intro to KGs. Parallel, shallower than CS520."),
]


STATIONS = [
    S("s-la-see", "See matrices", 0, "theory", "linear-algebra", [], "Geometry before Gaussian elimination.",
      do=["https://www.3blue1brown.com/topics/linear-algebra"],
      parallel=["https://www.khanacademy.org/math/linear-algebra", "https://mml-book.github.io/"],
      skim=["https://www.youtube.com/playlist?list=PLgMDNELGJ1CaTrBVbwaHoHYlTbyeV-q5c"],
      project=["https://github.com/fastai/numerical-linear-algebra"]),
    S("s-la-work", "Work matrices", 0, "practice", "linear-algebra", ["s-la-see"], "Four subspaces, least squares, SVD with problem sets.",
      do=["https://ocw.mit.edu/courses/18-06-linear-algebra-spring-2010/", "https://www.coursera.org/learn/linear-algebra-machine-learning"],
      parallel=["https://web.stanford.edu/~boyd/vmls/", "https://mml-book.github.io/"],
      skim=["https://ocw.mit.edu/courses/18-065-matrix-methods-in-data-analysis-signal-processing-and-machine-learning-spring-2018/"],
      project=["https://github.com/fastai/numerical-linear-algebra"]),
    S("s-calc", "Gradients that mean something", 0, "theory", "calculus", ["s-la-see"], "Backprop is multivariable calculus.",
      do=["https://www.3blue1brown.com/topics/calculus", "https://www.coursera.org/learn/multivariate-calculus-machine-learning"],
      parallel=["https://mml-book.github.io/"],
      skim=["https://www.khanacademy.org/math/linear-algebra"],
      project=["https://github.com/karpathy/micrograd"]),
    S("s-prob", "Uncertainty as a tool", 0, "practice", "probability", [], "Every loss is a likelihood in disguise.",
      do=["https://www.youtube.com/@statquest", "https://www.coursera.org/learn/machine-learning-probability-and-statistics"],
      parallel=["https://allendowney.github.io/ThinkBayes2/", "https://stat110.harvard.edu/"],
      skim=["https://ocw.mit.edu/courses/6-041-probabilistic-systems-analysis-and-applied-probability-fall-2010/"],
      project=["https://www.coursera.org/learn/pca-machine-learning"]),
    S("s-proofs", "Proofs without tears", 0, "theory", "theory", [], "Later SME theory dies if you cannot write a proof.",
      do=["https://ocw.mit.edu/courses/6-042j-mathematics-for-computer-science-fall-2010/"],
      parallel=["https://mml-book.github.io/"],
      skim=["http://ciml.info/"],
      project=["https://github.com/aimacode/aima-python"]),
    S("s-numerical", "Numbers that survive contact with a computer", 0, "practice", "linear-algebra", ["s-la-work"], "Conditioning, SVD in float64, not chalkboard.",
      do=["https://github.com/fastai/numerical-linear-algebra"],
      parallel=["https://ocw.mit.edu/courses/18-065-matrix-methods-in-data-analysis-signal-processing-and-machine-learning-spring-2018/"],
      skim=["https://web.stanford.edu/~boyd/vmls/"],
      project=["https://github.com/fastai/numerical-linear-algebra"]),
    S("s-ml-intuit", "Algorithms in English", 1, "theory", "classical-ml", ["s-prob"], "If you cannot draw it, you cannot debug it.",
      do=["https://www.youtube.com/@statquest"],
      parallel=["http://themlbook.com/", "https://mlu-explain.github.io/"],
      skim=["https://developers.google.com/machine-learning/crash-course"],
      project=["https://explained.ai/gradient-boosting/index.html"]),
    S("s-ml-do", "Train classical models", 1, "practice", "classical-ml", ["s-ml-intuit", "s-la-work"], "Labs plus a book that forces exercises.",
      do=["https://www.coursera.org/specializations/machine-learning-introduction", "https://www.statlearning.com/"],
      parallel=["https://scikit-learn.org/stable/user_guide.html", "https://www.oreilly.com/library/view/hands-on-machine-learning/9781098122461/"],
      skim=["https://developers.google.com/machine-learning/crash-course", "https://www.kaggle.com/learn", "https://www.youtube.com/playlist?list=PLgMDNELGJ1CYxkPswXfE1Fk9rzBeG4hFv"],
      project=["https://www.kaggle.com/competitions"]),
    S("s-unsupervised", "Structure without labels", 1, "practice", "classical-ml", ["s-ml-do"], "Clustering, density, PCA as geometry — not an afterthought week.",
      do=["https://www.statlearning.com/", "https://scikit-learn.org/stable/modules/clustering.html"],
      parallel=["https://www.coursera.org/learn/pca-machine-learning", "https://www.coursera.org/specializations/machine-learning-introduction"],
      skim=["https://mlu-explain.github.io/"],
      project=["https://scikit-learn.org/stable/modules/clustering.html"]),
    S("s-trees", "Trees and boosting", 1, "practice", "classical-ml", ["s-ml-do"], "Tabular SME is still GBM, not a tiny net.",
      do=["https://explained.ai/gradient-boosting/index.html", "https://xgboost.readthedocs.io/en/stable/tutorials/model.html"],
      parallel=["https://www.youtube.com/@statquest", "https://www.statlearning.com/"],
      skim=["https://scikit-learn.org/stable/user_guide.html"],
      project=["https://www.kaggle.com/competitions"]),
    S("s-eval", "Measure without lying", 1, "theory", "eval", ["s-ml-do"], "Leakage, calibration, slices. SME is distrusting a single accuracy.",
      do=["https://developers.google.com/machine-learning/guides/rules-of-ml", "https://mlu-explain.github.io/"],
      parallel=["https://www.statlearning.com/", "https://eugeneyan.com/writing/evals/"],
      skim=["https://scikit-learn.org/stable/modules/preprocessing.html"],
      project=["https://scikit-learn.org/stable/modules/preprocessing.html"]),
    S("s-search", "Search and planning", 1, "theory", "ai", [], "Classical AI: uninformed/informed search, MDPs as planning. Not sklearn.",
      do=["https://inst.eecs.berkeley.edu/~cs188/", "https://aima.cs.berkeley.edu/"],
      parallel=["https://stanford-cs221.github.io/"],
      skim=["https://www.youtube.com/playlist?list=PLgMDNELGJ1CZSGn478v1uKbzxJzKWZ7zs"],
      project=["https://github.com/aimacode/aima-python"]),
    S("s-logic", "Knowledge, SAT, constraints", 1, "theory", "ai", ["s-search"], "KR and logic. Agents without this become prompt soup.",
      do=["https://aima.cs.berkeley.edu/", "https://stanford-cs221.github.io/"],
      parallel=["https://inst.eecs.berkeley.edu/~cs188/"],
      skim=["https://www.youtube.com/playlist?list=PLgMDNELGJ1CZSGn478v1uKbzxJzKWZ7zs"],
      project=["https://github.com/aimacode/aima-python"]),
    S("s-games", "Adversaries and equilibria", 1, "theory", "ai", ["s-search"], "Minimax, MCTS, Nash. Games are AI, not a Kaggle metric.",
      do=["https://www.coursera.org/learn/game-theory-1", "https://www.nature.com/articles/nature16961"],
      parallel=["https://www.masfoundations.org/", "https://inst.eecs.berkeley.edu/~cs188/"],
      skim=["https://aima.cs.berkeley.edu/"],
      project=["https://github.com/aimacode/aima-python"]),
    S("s-kg", "Knowledge graphs", 1, "theory", "ai", ["s-logic"], "Structured knowledge for retrieval and neuro-symbolic work.",
      do=["https://web.stanford.edu/class/cs520/", "https://arxiv.org/abs/2003.02320"],
      parallel=["https://www.coursera.org/learn/ibm-knowledge-graphs", "https://nlp.stanford.edu/IR-book/"],
      skim=["https://aima.cs.berkeley.edu/"],
      project=["https://web.stanford.edu/class/cs520/"]),
    S("s-backprop", "Backprop from scalars", 2, "theory", "deep-learning", ["s-calc", "s-ml-do"], "Frameworks hide the only idea that matters.",
      do=["https://karpathy.ai/zero-to-hero.html", "https://github.com/karpathy/micrograd"],
      parallel=["http://neuralnetworksanddeeplearning.com/"],
      skim=["https://www.manning.com/books/grokking-deep-learning"],
      project=["https://github.com/karpathy/micrograd"]),
    S("s-ship-net", "Ship a working net", 2, "practice", "deep-learning", ["s-backprop"], "Top-down PyTorch for people who already write code.",
      do=["https://course.fast.ai/", "https://github.com/fastai/fastbook"],
      parallel=["https://www.coursera.org/specializations/deep-learning", "https://www.pluralsight.com/paths/building-deep-learning-solutions-with-pytorch", "https://pytorch.org/tutorials/"],
      skim=["https://d2l.ai/", "https://introtodeeplearning.com/", "https://www.youtube.com/playlist?list=PLgMDNELGJ1CaeIiQMBOE0NONdZxS2eD2H"],
      project=["https://course.fast.ai/Lessons/lesson1.html"]),
    S("s-cv", "See", 2, "theory", "computer-vision", ["s-ship-net"], "Conv nets, still the visual backbone.",
      do=["https://cs231n.stanford.edu/"],
      parallel=["https://huggingface.co/learn/computer-vision-course", "https://www.deeplearningbook.org/"],
      skim=["https://atcold.github.io/NYU-DLSP21/", "https://arxiv.org/abs/2304.02643"],
      project=["https://cs231n.github.io/assignments/2024/assignment1/"]),
    S("s-seq", "Sequences before transformers", 2, "theory", "nlp", ["s-backprop"], "RNNs/LSTMs so attention is a solution, not magic.",
      do=["https://colah.github.io/posts/2015-08-Understanding-LSTMs/", "https://www.coursera.org/specializations/deep-learning"],
      parallel=["https://www.deeplearningbook.org/", "https://d2l.ai/"],
      skim=["https://colah.github.io/"],
      project=["https://huggingface.co/learn/nlp-course/chapter7/1"]),
    S("s-ssl", "Learn without labels (deep)", 2, "practice", "computer-vision", ["s-cv"], "Contrastive, masked, frozen features. How modern vision actually starts.",
      do=["https://lilianweng.github.io/posts/2019-11-10-self-supervised/", "https://arxiv.org/abs/2002.05709"],
      parallel=["https://arxiv.org/abs/2304.07193", "https://huggingface.co/learn/computer-vision-course"],
      skim=["https://arxiv.org/abs/2304.02643"],
      project=["https://huggingface.co/learn/computer-vision-course"]),
    S("s-diffusion", "Generate pixels", 2, "practice", "diffusion", ["s-ship-net"], "VAE → GAN (history) → diffusion (now).",
      do=["https://huggingface.co/learn/diffusion-course", "https://lilianweng.github.io/posts/2021-07-11-diffusion-models/"],
      parallel=["https://arxiv.org/abs/2006.11239", "https://arxiv.org/abs/1312.6114"],
      skim=["https://arxiv.org/abs/1406.2661"],
      project=["https://huggingface.co/learn/diffusion-course"]),
    S("s-gnn", "Graphs", 2, "theory", "graphs", ["s-ship-net"], "Not everything is a grid or a sequence.",
      do=["https://web.stanford.edu/class/cs224w/", "https://distill.pub/2021/gnn-intro/"],
      parallel=["https://geometricdeeplearning.com/"],
      skim=["https://d2l.ai/"],
      project=["https://web.stanford.edu/class/cs224w/"]),
    S("s-attn", "Attention, then transformers", 3, "theory", "nlp", ["s-seq"], "Visual → implement → paper.",
      do=["https://jalammar.github.io/illustrated-transformer/", "https://karpathy.ai/zero-to-hero.html", "https://web.stanford.edu/class/cs224n/"],
      parallel=["https://nlp.seas.harvard.edu/annotated-transformer/", "https://arxiv.org/abs/1706.03762"],
      skim=["https://colah.github.io/", "https://web.stanford.edu/~jurafsky/slp3/", "https://web.stanford.edu/class/cs25/"],
      project=["https://github.com/karpathy/nanoGPT"]),
    S("s-ir", "Retrieve before you generate", 3, "theory", "nlp", ["s-ml-do"], "BM25 and IR eval before you wrap a vector DB.",
      do=["https://nlp.stanford.edu/IR-book/"],
      parallel=["https://web.stanford.edu/~jurafsky/slp3/"],
      skim=["https://nlp.stanford.edu/fsnlp/"],
      project=["https://huggingface.co/learn/nlp-course"]),
    S("s-llm-tools", "Language tools in production", 3, "practice", "generative", ["s-attn"], "Tokenizers, RAG, LoRA. After you could write GPT.",
      do=["https://huggingface.co/learn/nlp-course", "https://www.coursera.org/specializations/generative-ai-engineering-with-llms"],
      parallel=["https://www.pluralsight.com/paths/generative-ai-engineering-and-architecture", "https://huggingface.co/docs/peft/index", "https://arxiv.org/abs/2106.09685"],
      skim=["https://www.youtube.com/playlist?list=PLgMDNELGJ1Ca_DduFvH6qfI1eapL48xOr", "https://lilianweng.github.io/", "https://arxiv.org/abs/2401.04088"],
      project=["https://github.com/karpathy/nanoGPT"]),
    S("s-llm-from-scratch", "Language models from scratch (2025)", 3, "practice", "generative", ["s-attn"], "Data, tokenizer, train, eval — not only API calls.",
      do=["https://stanford-cs336.github.io/spring2025/", "https://github.com/karpathy/nanoGPT"],
      parallel=["https://karpathy.ai/zero-to-hero.html", "https://arxiv.org/abs/2205.14135"],
      skim=["https://web.stanford.edu/class/cs25/", "https://stanford-cs324.github.io/winter2022/"],
      project=["https://github.com/karpathy/nanoGPT"]),
    S("s-speech", "Hear", 3, "practice", "speech", ["s-attn"], "Waveforms are not text with a different file extension.",
      do=["https://huggingface.co/learn/audio-course", "https://arxiv.org/abs/2212.04356"],
      parallel=["https://web.stanford.edu/~jurafsky/slp3/"],
      skim=["https://github.com/openai/whisper"],
      project=["https://github.com/openai/whisper"]),
    S("s-llm-eval", "Judge models, not vibes", 3, "theory", "eval", ["s-llm-tools"], "HELM, harnesses, arena — and their failure modes.",
      do=["https://crfm.stanford.edu/helm/", "https://github.com/EleutherAI/lm-evaluation-harness"],
      parallel=["https://lmsys.org/blog/2023-05-03-arena/", "https://stanford-cs324.github.io/winter2022/"],
      skim=["https://www.anthropic.com/research"],
      project=["https://github.com/EleutherAI/lm-evaluation-harness"]),
    S("s-agents", "Tools, memory, loops", 3, "practice", "agents", ["s-llm-tools", "s-search"], "ReAct, tool use, memory. LLM agents after you can search and plan.",
      do=["https://huggingface.co/learn/agents-course", "https://lilianweng.github.io/posts/2023-06-23-agent/"],
      parallel=["https://arxiv.org/abs/2210.03629", "https://arxiv.org/abs/2302.04761", "https://www.pluralsight.com/paths/generative-ai-engineering-and-architecture"],
      skim=["https://www.anthropic.com/research"],
      project=["https://huggingface.co/learn/agents-course"]),
    S("s-agent-eval", "Eval agents, not chat", 3, "theory", "eval", ["s-agents", "s-llm-eval"], "GAIA, SWE-bench, τ-bench, function-calling. Different from MMLU.",
      do=["https://arxiv.org/abs/2311.12983", "https://www.swebench.com/"],
      parallel=["https://arxiv.org/abs/2406.12045", "https://arxiv.org/abs/2308.03688", "https://gorilla.cs.berkeley.edu/leaderboard.html"],
      skim=["https://arxiv.org/abs/2310.06770"],
      project=["https://www.swebench.com/"]),
    S("s-multimodal", "More than text", 3, "practice", "multimodal", ["s-cv", "s-attn"], "CLIP → visual instruction tuning.",
      do=["https://arxiv.org/abs/2103.00020", "https://arxiv.org/abs/2304.08485"],
      parallel=["https://huggingface.co/learn/computer-vision-course"],
      skim=["https://web.stanford.edu/class/cs25/"],
      project=["https://huggingface.co/learn/computer-vision-course"]),
    S("s-code-llm", "Models that write programs", 3, "practice", "code-llm", ["s-llm-tools"], "Data, eval (HumanEval lineage), not only Copilot demos.",
      do=["https://arxiv.org/abs/2107.03374", "https://arxiv.org/abs/2211.15533"],
      parallel=["https://github.com/karpathy/nanoGPT", "https://huggingface.co/learn/nlp-course"],
      skim=["https://stanford-cs336.github.io/spring2025/"],
      project=["https://github.com/karpathy/nanoGPT"]),
    S("s-ssm", "State space vs attention", 3, "theory", "ssm", ["s-attn"], "S4 → Mamba. Know the alternative, don't marry it.",
      do=["https://arxiv.org/abs/2111.00396", "https://arxiv.org/abs/2312.00752"],
      parallel=["https://github.com/state-spaces/mamba"],
      skim=["https://web.stanford.edu/class/cs25/"],
      project=["https://github.com/state-spaces/mamba"]),
    S("s-rl", "Decisions, not labels", 4, "theory", "rl", ["s-ml-do"], "MDPs before DQN memes.",
      do=["https://www.youtube.com/playlist?list=PLqYmG7hTraZDM-OYHWgPebj2MfCFzFObQ", "http://incompleteideas.net/book/the-book-2nd.html"],
      parallel=["https://www.coursera.org/specializations/reinforcement-learning", "https://web.stanford.edu/class/cs234/"],
      skim=["https://www.youtube.com/playlist?list=PLgMDNELGJ1CaCugN_GPrVQUkGUCAKZF2s"],
      project=["https://gymnasium.farama.org/"]),
    S("s-drl", "Play", 4, "practice", "rl", ["s-rl", "s-ship-net"], "Deep RL is a different sport.",
      do=["https://huggingface.co/learn/deep-rl-course/en/unit0/introduction", "https://spinningup.openai.com/en/latest/"],
      parallel=["https://rail.eecs.berkeley.edu/deeprlcourse/", "https://gymnasium.farama.org/"],
      skim=["https://arxiv.org/abs/2106.01345"],
      project=["https://huggingface.co/learn/deep-rl-course/en/unit0/introduction"]),
    S("s-bandits", "Explore vs exploit", 4, "theory", "bandits", ["s-prob"], "Before full MDPs, or you will misuse ε-greedy forever.",
      do=["https://tor-lattimore.com/downloads/book/book.pdf"],
      parallel=["http://incompleteideas.net/book/the-book-2nd.html"],
      skim=["https://www.coursera.org/specializations/reinforcement-learning"],
      project=["https://gymnasium.farama.org/"]),
    S("s-imitation", "Copy, then improve", 4, "practice", "imitation", ["s-rl"], "DAgger lineage + offline RL as sequence models.",
      do=["https://arxiv.org/abs/2106.01345", "https://spinningup.openai.com/en/latest/"],
      parallel=["https://rail.eecs.berkeley.edu/deeprlcourse/"],
      skim=["http://incompleteideas.net/book/the-book-2nd.html"],
      project=["https://gymnasium.farama.org/"]),
    S("s-marl", "Other agents exist", 4, "theory", "marl", ["s-rl"], "Non-stationarity is the point.",
      do=["https://www.marl-book.com/"],
      parallel=["https://rail.eecs.berkeley.edu/deeprlcourse/"],
      skim=["https://huggingface.co/learn/deep-rl-course/en/unit0/introduction"],
      project=["https://gymnasium.farama.org/"]),
    S("s-world-models", "Imagine the environment", 4, "practice", "world-models", ["s-drl", "s-diffusion"], "World models, Dreamer, video-as-simulator interest.",
      do=["https://worldmodels.github.io/", "https://arxiv.org/abs/2301.04104"],
      parallel=["https://huggingface.co/learn/deep-rl-course/en/unit0/introduction"],
      skim=["https://rail.eecs.berkeley.edu/deeprlcourse/"],
      project=["https://worldmodels.github.io/"]),
    S("s-data-ml", "Data-centric", 5, "theory", "data-centric", ["s-eval"], "The dataset is the model.",
      do=["https://dcai.csail.mit.edu/", "https://www.deeplearning.ai/short-courses/data-centric-ai/"],
      parallel=["https://developers.google.com/machine-learning/guides/rules-of-ml"],
      skim=["https://scikit-learn.org/stable/modules/preprocessing.html"],
      project=["https://dcai.csail.mit.edu/"]),
    S("s-sys", "Make it real", 5, "practice", "mlsys", ["s-ship-net"], "A notebook is not a system.",
      do=["https://github.com/chiphuyen/machine-learning-systems-design", "https://madewithml.com/"],
      parallel=["https://www.pluralsight.com/paths/machine-learning-engineering", "https://www.coursera.org/specializations/machine-learning-engineering-for-production-mlops", "https://fullstackdeeplearning.com/"],
      skim=["https://www.youtube.com/playlist?list=PLgMDNELGJ1CY3kDa1Y3hJI3h4TOoO3Dsq"],
      project=["https://madewithml.com/"]),
    S("s-eval-prod", "Eval in production", 5, "practice", "eval", ["s-sys", "s-eval"], "Monitoring, drift, LLM evals in the loop.",
      do=["https://eugeneyan.com/writing/evals/", "https://crfm.stanford.edu/helm/"],
      parallel=["https://github.com/EleutherAI/lm-evaluation-harness"],
      skim=["https://lmsys.org/blog/2023-05-03-arena/"],
      project=["https://github.com/EleutherAI/lm-evaluation-harness"]),
    S("s-compilers", "Kernels, compilers, FLOPs", 5, "theory", "compilers", ["s-attn"], "FlashAttention, torch.compile, CUDA Mode.",
      do=["https://github.com/cuda-mode/lectures", "https://arxiv.org/abs/2205.14135"],
      parallel=["https://pytorch.org/tutorials/intermediate/torch_compile_tutorial.html"],
      skim=["https://www.youtube.com/playlist?list=PLgMDNELGJ1CY3kDa1Y3hJI3h4TOoO3Dsq"],
      project=["https://pytorch.org/tutorials/intermediate/torch_compile_tutorial.html"]),
    S("s-privacy", "Privacy and federated", 5, "theory", "privacy", ["s-ml-do"], "DP is math. Federated is a systems constraint.",
      do=["https://www.cis.upenn.edu/~aaroth/Papers/privacybook.pdf"],
      parallel=["https://arxiv.org/abs/1602.05629"],
      skim=["https://github.com/chiphuyen/machine-learning-systems-design"],
      project=["https://madewithml.com/"]),
    S("s-theory", "Why it generalizes", 6, "theory", "theory", ["s-ml-do", "s-la-work"], "SME is saying when a bound exists.",
      do=["https://work.caltech.edu/telecourse.html", "https://cs229.stanford.edu/"],
      parallel=["https://www.cs.huji.ac.il/~shais/UnderstandingMachineLearning/", "http://ciml.info/", "https://web.stanford.edu/~hastie/ElemStatLearn/"],
      skim=["https://www.youtube.com/playlist?list=PLgMDNELGJ1Cay-Q9Cn8KcpUcC58NDWuiu", "https://www.youtube.com/playlist?list=PLgMDNELGJ1CZp3yTR9r5utkisB8i92_dZ"],
      project=["https://cs229.stanford.edu/"]),
    S("s-prob-sme", "Bayesian desk", 6, "theory", "probability", ["s-prob", "s-theory"], "Pick one thick book and live in it.",
      do=["https://probml.github.io/pml-book/book1.html"],
      parallel=["https://www.microsoft.com/en-us/research/uploads/prod/2006/01/Bishop-Pattern-Recognition-and-Machine-Learning-2006.pdf"],
      skim=["https://www.coursera.org/specializations/probabilistic-graphical-models"],
      project=["https://camdavidsonpilon.github.io/Probabilistic-Programming-and-Bayesian-Methods-for-Hackers/"]),
    S("s-opt", "Convex and beyond", 6, "theory", "optimization", ["s-calc"], "SGD folklore vs real convex analysis.",
      do=["https://web.stanford.edu/~boyd/cvxbook/bv_cvxbook.pdf"],
      parallel=["https://web.stanford.edu/~boyd/papers/cvx_short_course.html"],
      skim=["https://www.youtube.com/playlist?list=PLgMDNELGJ1CaCugN_GPrVQUkGUCAKZF2s"],
      project=["https://web.stanford.edu/~boyd/papers/cvx_short_course.html"]),
    S("s-info-theory", "Bits, KL, and learning", 6, "theory", "info-theory", ["s-prob"], "Cross-entropy is not just a Keras argument.",
      do=["https://www.inference.org.uk/mackay/itila/"],
      parallel=["https://probml.github.io/pml-book/book1.html"],
      skim=["https://www.youtube.com/playlist?list=PLgMDNELGJ1CYS-8dlMGPIaowVfeda4nUj"],
      project=["https://www.inference.org.uk/mackay/itila/"]),
    S("s-pgm", "Graphical models", 6, "theory", "pgm", ["s-prob-sme"], "Independence, inference, latent variables — not only neural nets.",
      do=["https://www.coursera.org/specializations/probabilistic-graphical-models", "https://ermongroup.github.io/cs228-notes/"],
      parallel=["https://probml.github.io/pml-book/book1.html"],
      skim=["https://aima.cs.berkeley.edu/"],
      project=["https://ermongroup.github.io/cs228-notes/"]),
    S("s-causal", "Cause, not correlation", 7, "practice", "causal", ["s-ml-do", "s-eval"], "Do-calculus, identification, not just a DAG sticker.",
      do=["https://matheusfacure.github.io/python-causality-handbook/landing-page.html", "https://www.bradyneal.com/causal-inference-course"],
      parallel=["http://bayes.cs.ucla.edu/WHY/", "https://www.hsph.harvard.edu/miguel-hernan/causal-inference-book/"],
      skim=["https://fairmlbook.org/"],
      project=["https://matheusfacure.github.io/python-causality-handbook/landing-page.html"]),
    S("s-recommenders", "Rank things for people", 7, "practice", "recommenders", ["s-ml-do"], "Retrieval and ranking systems, not a cosine demo.",
      do=["https://developers.google.com/machine-learning/recommendation", "https://www.coursera.org/specializations/recommender-systems"],
      parallel=["https://www.statlearning.com/"],
      skim=["https://nlp.stanford.edu/IR-book/"],
      project=["https://developers.google.com/machine-learning/recommendation"]),
    S("s-timeseries", "Time is not an iid row", 7, "practice", "timeseries", ["s-ml-do"], "Forecasting first, then sequence models.",
      do=["https://otexts.com/fpp3/", "https://www.sktime.net/en/stable/"],
      parallel=["https://www.statlearning.com/"],
      skim=["https://d2l.ai/"],
      project=["https://www.sktime.net/en/stable/"]),
    S("s-robotics", "Bodies", 7, "practice", "robotics", ["s-rl", "s-cv"], "Control, manipulation, LeRobot. Embodied interest is not a blog post.",
      do=["https://underactuated.csail.mit.edu/", "https://github.com/huggingface/lerobot"],
      parallel=["https://manipulation.csail.mit.edu/", "https://www.coursera.org/specializations/modernrobotics"],
      skim=["https://worldmodels.github.io/"],
      project=["https://github.com/huggingface/lerobot"]),
    S("s-scientific-ml", "Science as a loss function", 7, "theory", "scientific-ml", ["s-ship-net", "s-opt"], "PINNs, neural ODEs, AlphaFold as existence proof.",
      do=["https://arxiv.org/abs/1711.10561", "https://arxiv.org/abs/1806.07366"],
      parallel=["https://www.nature.com/articles/s41586-021-03819-2"],
      skim=["https://d2l.ai/"],
      project=["https://arxiv.org/abs/1711.10561"]),
    S("s-interp", "Look inside", 7, "theory", "interpretability", ["s-attn"], "Mech interp, circuits, TransformerLens.",
      do=["https://www.neelnanda.io/mechanistic-interpretability/getting-started", "https://transformerlensorg.github.io/TransformerLens/"],
      parallel=["https://distill.pub/2020/circuits/", "https://www.arena.education/"],
      skim=["https://colah.github.io/"],
      project=["https://transformerlensorg.github.io/TransformerLens/"]),
    S("s-alignment", "What we asked vs what we got", 7, "theory", "alignment", ["s-llm-tools", "s-rl"], "RLHF, DPO, constitutions, process reward.",
      do=["https://arxiv.org/abs/2203.02155", "https://arxiv.org/abs/2305.18290"],
      parallel=["https://arxiv.org/abs/2212.08073", "https://huggingface.co/blog/rlhf", "https://course.aisafetyfundamentals.com/"],
      skim=["https://www.arena.education/", "https://arxiv.org/abs/2501.12948"],
      project=["https://huggingface.co/blog/rlhf"]),
    S("s-test-time", "Think at inference", 7, "practice", "generative", ["s-alignment", "s-llm-eval"], "CoT, verifiers, reasoning models (o1/R1 lineage).",
      do=["https://arxiv.org/abs/2201.11903", "https://arxiv.org/abs/2305.20050"],
      parallel=["https://arxiv.org/abs/2501.12948"],
      skim=["https://lmsys.org/blog/2023-05-03-arena/"],
      project=["https://github.com/EleutherAI/lm-evaluation-harness"]),
    S("s-3d-vision", "Space", 7, "practice", "3d-vision", ["s-cv"], "NeRF → Gaussian splatting.",
      do=["https://arxiv.org/abs/2003.08934", "https://repo-sam.inria.fr/fungraph/3d-gaussian-splatting/"],
      parallel=["https://www.matthewtancik.com/nerf"],
      skim=["https://huggingface.co/learn/computer-vision-course"],
      project=["https://www.matthewtancik.com/nerf"]),
    S("s-fairness", "Who the model fails", 7, "theory", "fairness", ["s-eval"], "Not an ethics slide. Definitions and impossibility results.",
      do=["https://fairmlbook.org/"],
      parallel=["https://developers.google.com/machine-learning/guides/rules-of-ml"],
      skim=["https://mlu-explain.github.io/"],
      project=["https://fairmlbook.org/"]),
]
