"""Lesson outlines for Do-rail courses. Keys are normalized parent URLs."""

from __future__ import annotations

OUTLINES: dict[str, list[dict]] = {
    "https://3blue1brown.com/topics/linear-algebra": [
        {"slug": "vectors", "title": "Vectors", "url": "https://www.3blue1brown.com/lessons/vectors"},
        {"slug": "span", "title": "Linear combinations, span, basis", "url": "https://www.3blue1brown.com/lessons/span"},
        {"slug": "linear-transformations", "title": "Linear transformations", "url": "https://www.3blue1brown.com/lessons/linear-transformations"},
        {"slug": "matrix-multiplication", "title": "Matrix multiplication", "url": "https://www.3blue1brown.com/lessons/matrix-multiplication"},
        {"slug": "3d-transformations", "title": "3D transformations", "url": "https://www.3blue1brown.com/lessons/3d-transformations"},
        {"slug": "determinant", "title": "Determinants", "url": "https://www.3blue1brown.com/lessons/determinant"},
        {"slug": "inverse-matrices", "title": "Inverse matrices, column space, null space", "url": "https://www.3blue1brown.com/lessons/inverse-matrices"},
        {"slug": "nonsquare-matrices", "title": "Nonsquare matrices", "url": "https://www.3blue1brown.com/lessons/nonsquare-matrices"},
        {"slug": "dot-products", "title": "Dot products", "url": "https://www.3blue1brown.com/lessons/dot-products"},
        {"slug": "cross-products", "title": "Cross products", "url": "https://www.3blue1brown.com/lessons/cross-products"},
        {"slug": "cross-products-extended", "title": "Cross products in 3d", "url": "https://www.3blue1brown.com/lessons/cross-products-extended"},
        {"slug": "cramers-rule", "title": "Cramer's rule", "url": "https://www.3blue1brown.com/lessons/cramers-rule"},
        {"slug": "change-of-basis", "title": "Change of basis", "url": "https://www.3blue1brown.com/lessons/change-of-basis"},
        {"slug": "eigenvalues", "title": "Eigenvalues and eigenvectors", "url": "https://www.3blue1brown.com/lessons/eigenvalues"},
        {"slug": "abstract-vector-spaces", "title": "Abstract vector spaces", "url": "https://www.3blue1brown.com/lessons/abstract-vector-spaces"},
    ],
    "https://3blue1brown.com/topics/calculus": [
        {"slug": "essence-of-calculus", "title": "The essence of calculus", "url": "https://www.3blue1brown.com/lessons/essence-of-calculus"},
        {"slug": "chain-rule", "title": "Chain rule and product rule", "url": "https://www.3blue1brown.com/lessons/chain-rule-and-product-rule"},
        {"slug": "eulers-number", "title": "Euler's number", "url": "https://www.3blue1brown.com/lessons/eulers-number"},
        {"slug": "implicit-differentiation", "title": "Implicit differentiation", "url": "https://www.3blue1brown.com/lessons/implicit-differentiation"},
        {"slug": "limits", "title": "Limits", "url": "https://www.3blue1brown.com/lessons/limits"},
        {"slug": "integration", "title": "Integration", "url": "https://www.3blue1brown.com/lessons/integration"},
        {"slug": "area-and-slope", "title": "Area and slope", "url": "https://www.3blue1brown.com/lessons/area-and-slope"},
        {"slug": "higher-order-derivatives", "title": "Higher-order derivatives", "url": "https://www.3blue1brown.com/lessons/higher-order-derivatives"},
        {"slug": "taylor-series", "title": "Taylor series", "url": "https://www.3blue1brown.com/lessons/taylor-series"},
    ],
    "https://course.fast.ai": [
        {"slug": "lesson1", "title": "Lesson 1", "url": "https://course.fast.ai/Lessons/lesson1.html"},
        {"slug": "lesson2", "title": "Lesson 2", "url": "https://course.fast.ai/Lessons/lesson2.html"},
        {"slug": "lesson3", "title": "Lesson 3", "url": "https://course.fast.ai/Lessons/lesson3.html"},
        {"slug": "lesson4", "title": "Lesson 4", "url": "https://course.fast.ai/Lessons/lesson4.html"},
        {"slug": "lesson5", "title": "Lesson 5", "url": "https://course.fast.ai/Lessons/lesson5.html"},
        {"slug": "lesson6", "title": "Lesson 6", "url": "https://course.fast.ai/Lessons/lesson6.html"},
        {"slug": "lesson7", "title": "Lesson 7", "url": "https://course.fast.ai/Lessons/lesson7.html"},
        {"slug": "lesson8", "title": "Lesson 8", "url": "https://course.fast.ai/Lessons/lesson8.html"},
    ],
    "https://coursera.org/specializations/machine-learning-introduction": [
        {"slug": "week-1", "title": "Week 1", "url": None},
        {"slug": "week-2", "title": "Week 2", "url": None},
        {"slug": "week-3", "title": "Week 3", "url": None},
        {"slug": "week-4", "title": "Week 4", "url": None},
        {"slug": "week-5", "title": "Week 5", "url": None},
        {"slug": "week-6", "title": "Week 6", "url": None},
    ],
    "https://coursera.org/learn/linear-algebra-machine-learning": [
        {"slug": "week-1", "title": "Week 1", "url": None},
        {"slug": "week-2", "title": "Week 2", "url": None},
        {"slug": "week-3", "title": "Week 3", "url": None},
        {"slug": "week-4", "title": "Week 4", "url": None},
        {"slug": "week-5", "title": "Week 5", "url": None},
    ],
    "https://coursera.org/learn/multivariate-calculus-machine-learning": [
        {"slug": "week-1", "title": "Week 1", "url": None},
        {"slug": "week-2", "title": "Week 2", "url": None},
        {"slug": "week-3", "title": "Week 3", "url": None},
        {"slug": "week-4", "title": "Week 4", "url": None},
    ],
    "https://karpathy.ai/zero-to-hero.html": [
        {"slug": "micrograd", "title": "micrograd: backprop from scratch", "url": "https://www.youtube.com/watch?v=VMj-3S1tku0"},
        {"slug": "makemore-1", "title": "makemore part 1: language modeling", "url": "https://www.youtube.com/watch?v=PaCmpygFfXo"},
        {"slug": "makemore-2", "title": "makemore part 2: MLP", "url": "https://www.youtube.com/watch?v=TCH_1BHY58I"},
        {"slug": "makemore-3", "title": "makemore part 3: activations, gradients, BatchNorm", "url": "https://www.youtube.com/watch?v=P6sfmUTpUmc"},
        {"slug": "makemore-4", "title": "makemore part 4: backprop ninja", "url": "https://www.youtube.com/watch?v=q8SA3rM6ckI"},
        {"slug": "makemore-5", "title": "makemore part 5: WaveNet", "url": "https://www.youtube.com/watch?v=t3YJ5hKiMQ0"},
        {"slug": "gpt", "title": "Let's build GPT", "url": "https://www.youtube.com/watch?v=kCc8FmEb1nY"},
        {"slug": "tokenizer", "title": "Let's build the GPT tokenizer", "url": "https://www.youtube.com/watch?v=zduSFxRajkE"},
    ],
    "https://huggingface.co/learn/nlp-course": [
        {"slug": "chapter-1", "title": "Chapter 1: Introduction", "url": "https://huggingface.co/learn/nlp-course/chapter1/1"},
        {"slug": "chapter-2", "title": "Chapter 2: Using Transformers", "url": "https://huggingface.co/learn/nlp-course/chapter2/1"},
        {"slug": "chapter-3", "title": "Chapter 3: Fine-tuning", "url": "https://huggingface.co/learn/nlp-course/chapter3/1"},
        {"slug": "chapter-4", "title": "Chapter 4: Sharing models and tokenizers", "url": "https://huggingface.co/learn/nlp-course/chapter4/1"},
        {"slug": "chapter-5", "title": "Chapter 5: Datasets", "url": "https://huggingface.co/learn/nlp-course/chapter5/1"},
        {"slug": "chapter-6", "title": "Chapter 6: Tokenizers", "url": "https://huggingface.co/learn/nlp-course/chapter6/1"},
        {"slug": "chapter-7", "title": "Chapter 7: Main NLP tasks", "url": "https://huggingface.co/learn/nlp-course/chapter7/1"},
        {"slug": "chapter-8", "title": "Chapter 8: How to ask for help", "url": "https://huggingface.co/learn/nlp-course/chapter8/1"},
        {"slug": "chapter-9", "title": "Chapter 9: Building and sharing demos", "url": "https://huggingface.co/learn/nlp-course/chapter9/1"},
    ],
    "https://ocw.mit.edu/courses/18-06-linear-algebra-spring-2010": [
        {"slug": "lec-1", "title": "Lecture 1: The geometry of linear equations", "url": "https://ocw.mit.edu/courses/18-06-linear-algebra-spring-2010/resources/lecture-1-the-geometry-of-linear-equations/"},
        {"slug": "lec-2", "title": "Lecture 2: Elimination with matrices", "url": "https://ocw.mit.edu/courses/18-06-linear-algebra-spring-2010/resources/lecture-2-elimination-with-matrices/"},
        {"slug": "lec-3", "title": "Lecture 3: Multiplication and inverse matrices", "url": "https://ocw.mit.edu/courses/18-06-linear-algebra-spring-2010/resources/lecture-3-multiplication-and-inverse-matrices/"},
        {"slug": "lec-4", "title": "Lecture 4: Factorization into A = LU", "url": "https://ocw.mit.edu/courses/18-06-linear-algebra-spring-2010/resources/lecture-4-factorization-into-a-lu/"},
        {"slug": "lec-5", "title": "Lecture 5: Transposes, permutations, spaces Rⁿ", "url": "https://ocw.mit.edu/courses/18-06-linear-algebra-spring-2010/resources/lecture-5-transposes-permutations-spaces-r-n/"},
        {"slug": "lec-6", "title": "Lecture 6: Column space and nullspace", "url": "https://ocw.mit.edu/courses/18-06-linear-algebra-spring-2010/resources/lecture-6-column-space-and-nullspace/"},
        {"slug": "lec-7", "title": "Lecture 7: Solving Ax = 0", "url": "https://ocw.mit.edu/courses/18-06-linear-algebra-spring-2010/resources/lecture-7-solving-ax-0-pivot-variables-special-solutions/"},
        {"slug": "lec-8", "title": "Lecture 8: Solving Ax = b", "url": "https://ocw.mit.edu/courses/18-06-linear-algebra-spring-2010/resources/lecture-8-solving-ax-b-row-reduced-form-r/"},
        {"slug": "lec-9", "title": "Lecture 9: Independence, basis, and dimension", "url": "https://ocw.mit.edu/courses/18-06-linear-algebra-spring-2010/resources/lecture-9-independence-basis-and-dimension/"},
        {"slug": "lec-10", "title": "Lecture 10: The four fundamental subspaces", "url": "https://ocw.mit.edu/courses/18-06-linear-algebra-spring-2010/resources/lecture-10-the-four-fundamental-subspaces/"},
        {"slug": "lec-11", "title": "Lecture 11: Matrix spaces; rank 1", "url": "https://ocw.mit.edu/courses/18-06-linear-algebra-spring-2010/resources/lecture-11-matrix-spaces-rank-1-small-world-graphs/"},
        {"slug": "lec-12", "title": "Lecture 12: Graphs, networks, incidence matrices", "url": "https://ocw.mit.edu/courses/18-06-linear-algebra-spring-2010/resources/lecture-12-graphs-networks-incidence-matrices/"},
        {"slug": "lec-14", "title": "Lecture 14: Orthogonal vectors and subspaces", "url": "https://ocw.mit.edu/courses/18-06-linear-algebra-spring-2010/resources/lecture-14-orthogonal-vectors-and-subspaces/"},
        {"slug": "lec-15", "title": "Lecture 15: Projections onto subspaces", "url": "https://ocw.mit.edu/courses/18-06-linear-algebra-spring-2010/resources/lecture-15-projections-onto-subspaces/"},
        {"slug": "lec-16", "title": "Lecture 16: Projection matrices and least squares", "url": "https://ocw.mit.edu/courses/18-06-linear-algebra-spring-2010/resources/lecture-16-projection-matrices-and-least-squares/"},
        {"slug": "lec-17", "title": "Lecture 17: Orthogonal matrices and Gram-Schmidt", "url": "https://ocw.mit.edu/courses/18-06-linear-algebra-spring-2010/resources/lecture-17-orthogonal-matrices-and-gram-schmidt/"},
        {"slug": "lec-18", "title": "Lecture 18: Properties of determinants", "url": "https://ocw.mit.edu/courses/18-06-linear-algebra-spring-2010/resources/lecture-18-properties-of-determinants/"},
        {"slug": "lec-19", "title": "Lecture 19: Determinant formulas and cofactors", "url": "https://ocw.mit.edu/courses/18-06-linear-algebra-spring-2010/resources/lecture-19-determinant-formulas-and-cofactors/"},
        {"slug": "lec-20", "title": "Lecture 20: Cramer's rule, inverse matrix, and volume", "url": "https://ocw.mit.edu/courses/18-06-linear-algebra-spring-2010/resources/lecture-20-cramers-rule-inverse-matrix-and-volume/"},
        {"slug": "lec-21", "title": "Lecture 21: Eigenvalues and eigenvectors", "url": "https://ocw.mit.edu/courses/18-06-linear-algebra-spring-2010/resources/lecture-21-eigenvalues-and-eigenvectors/"},
        {"slug": "lec-22", "title": "Lecture 22: Diagonalization and powers of A", "url": "https://ocw.mit.edu/courses/18-06-linear-algebra-spring-2010/resources/lecture-22-diagonalization-and-powers-of-a/"},
        {"slug": "lec-23", "title": "Lecture 23: Differential equations and exp(At)", "url": "https://ocw.mit.edu/courses/18-06-linear-algebra-spring-2010/resources/lecture-23-differential-equations-and-exp-at/"},
        {"slug": "lec-24", "title": "Lecture 24: Markov matrices; Fourier series", "url": "https://ocw.mit.edu/courses/18-06-linear-algebra-spring-2010/resources/lecture-24-markov-matrices-fourier-series/"},
        {"slug": "lec-30", "title": "Lecture 30: Linear transformations and their matrices", "url": "https://ocw.mit.edu/courses/18-06-linear-algebra-spring-2010/resources/lecture-30-linear-transformations-and-their-matrices/"},
        {"slug": "lec-33", "title": "Lecture 33: Left and right inverses; pseudoinverse", "url": "https://ocw.mit.edu/courses/18-06-linear-algebra-spring-2010/resources/lecture-33-left-and-right-inverses-pseudoinverse/"},
        {"slug": "lec-34", "title": "Lecture 34: Final course review", "url": "https://ocw.mit.edu/courses/18-06-linear-algebra-spring-2010/resources/lecture-34-final-course-review/"},
    ],
    "https://statlearning.com": [
        {"slug": "ch2", "title": "Chapter 2: Statistical learning", "url": None},
        {"slug": "ch3", "title": "Chapter 3: Linear regression", "url": None},
        {"slug": "ch4", "title": "Chapter 4: Classification", "url": None},
        {"slug": "ch5", "title": "Chapter 5: Resampling methods", "url": None},
        {"slug": "ch6", "title": "Chapter 6: Linear model selection and regularization", "url": None},
        {"slug": "ch8", "title": "Chapter 8: Tree-based methods", "url": None},
        {"slug": "ch12", "title": "Chapter 12: Unsupervised learning", "url": None},
    ],
    "https://huggingface.co/learn/diffusion-course": [
        {"slug": "unit-0", "title": "Unit 0: Welcome", "url": "https://huggingface.co/learn/diffusion-course/unit0/1"},
        {"slug": "unit-1", "title": "Unit 1: Introduction to diffusers", "url": "https://huggingface.co/learn/diffusion-course/unit1/1"},
        {"slug": "unit-2", "title": "Unit 2: Fine-tuning", "url": "https://huggingface.co/learn/diffusion-course/unit2/1"},
        {"slug": "unit-3", "title": "Unit 3: Stable Diffusion", "url": "https://huggingface.co/learn/diffusion-course/unit3/1"},
        {"slug": "unit-4", "title": "Unit 4: Beyond the basics", "url": "https://huggingface.co/learn/diffusion-course/unit4/1"},
    ],
    "https://huggingface.co/learn/audio-course": [
        {"slug": "chapter-1", "title": "Chapter 1", "url": "https://huggingface.co/learn/audio-course/chapter1"},
        {"slug": "chapter-2", "title": "Chapter 2", "url": "https://huggingface.co/learn/audio-course/chapter2"},
        {"slug": "chapter-3", "title": "Chapter 3", "url": "https://huggingface.co/learn/audio-course/chapter3"},
        {"slug": "chapter-4", "title": "Chapter 4", "url": "https://huggingface.co/learn/audio-course/chapter4"},
        {"slug": "chapter-5", "title": "Chapter 5", "url": "https://huggingface.co/learn/audio-course/chapter5"},
    ],
    "https://cs231n.stanford.edu": [
        {"slug": "classification", "title": "Image classification notes", "url": "https://cs231n.github.io/classification/"},
        {"slug": "convnets", "title": "Convolutional networks notes", "url": "https://cs231n.github.io/convolutional-networks/"},
    ],
    "https://ocw.mit.edu/courses/6-042j-mathematics-for-computer-science-fall-2010": [
        {"slug": "lec-1", "title": "Lecture 1: Introduction and proofs", "url": "https://ocw.mit.edu/courses/6-042j-mathematics-for-computer-science-fall-2010/resources/lecture-1-introduction-and-proofs/"},
        {"slug": "lec-2", "title": "Lecture 2: Induction", "url": "https://ocw.mit.edu/courses/6-042j-mathematics-for-computer-science-fall-2010/resources/lecture-2-induction/"},
        {"slug": "lec-3", "title": "Lecture 3: Strong induction", "url": "https://ocw.mit.edu/courses/6-042j-mathematics-for-computer-science-fall-2010/resources/lecture-3-strong-induction/"},
        {"slug": "lec-4", "title": "Lecture 4: Number theory I", "url": "https://ocw.mit.edu/courses/6-042j-mathematics-for-computer-science-fall-2010/resources/lecture-4-number-theory-i/"},
        {"slug": "lec-5", "title": "Lecture 5: Number theory II", "url": "https://ocw.mit.edu/courses/6-042j-mathematics-for-computer-science-fall-2010/resources/lecture-5-number-theory-ii/"},
        {"slug": "lec-6", "title": "Lecture 6: Graph theory and coloring", "url": "https://ocw.mit.edu/courses/6-042j-mathematics-for-computer-science-fall-2010/resources/lecture-6-graph-theory-and-coloring/"},
        {"slug": "lec-7", "title": "Lecture 7: Matching problems", "url": "https://ocw.mit.edu/courses/6-042j-mathematics-for-computer-science-fall-2010/resources/lecture-7-matching-problems/"},
    ],
    "https://inst.eecs.berkeley.edu/~cs188": [
        {"slug": "proj-search", "title": "Project 1: Search", "url": None},
        {"slug": "proj-multiagent", "title": "Project 2: Multi-agent search", "url": None},
        {"slug": "proj-rl", "title": "Project 3: Reinforcement learning", "url": None},
        {"slug": "proj-bayes", "title": "Project 4: Ghostbusters / Bayes nets", "url": None},
        {"slug": "proj-ml", "title": "Project 5: Machine learning", "url": None},
    ],
    "https://huggingface.co/learn/agents-course": [
        {"slug": "unit-1", "title": "Unit 1: Introduction to agents", "url": "https://huggingface.co/learn/agents-course/unit1/introduction"},
        {"slug": "unit-2", "title": "Unit 2: Frameworks", "url": "https://huggingface.co/learn/agents-course/unit2/introduction"},
        {"slug": "bonus-1", "title": "Bonus unit 1", "url": "https://huggingface.co/learn/agents-course/bonus-unit1/introduction"},
    ],
    "https://youtube.com/@statquest": [
        {"slug": "mean-std", "title": "Mean, variance, and standard deviation", "url": None},
        {"slug": "p-values", "title": "p-values", "url": None},
        {"slug": "linear-regression", "title": "Linear regression", "url": None},
        {"slug": "logistic-regression", "title": "Logistic regression", "url": None},
        {"slug": "pca", "title": "PCA", "url": None},
    ],
    "https://aima.cs.berkeley.edu": [
        {"slug": "ch3", "title": "Chapter 3: Solving problems by searching", "url": None},
        {"slug": "ch4", "title": "Chapter 4: Search in complex environments", "url": None},
        {"slug": "ch6", "title": "Chapter 6: Constraint satisfaction", "url": None},
        {"slug": "ch7", "title": "Chapter 7: Logical agents", "url": None},
        {"slug": "ch17", "title": "Chapter 17: Making complex decisions", "url": None},
    ],
    "https://coursera.org/learn/game-theory-1": [
        {"slug": "week-1", "title": "Week 1", "url": None},
        {"slug": "week-2", "title": "Week 2", "url": None},
        {"slug": "week-3", "title": "Week 3", "url": None},
        {"slug": "week-4", "title": "Week 4", "url": None},
    ],
    "https://web.stanford.edu/class/cs224w": [
        {"slug": "week-1", "title": "Week 1: Introduction", "url": None},
        {"slug": "week-2", "title": "Week 2: Node embeddings", "url": None},
        {"slug": "week-3", "title": "Week 3: Graph neural networks", "url": None},
        {"slug": "week-4", "title": "Week 4: GNN training", "url": None},
    ],
    "https://web.stanford.edu/class/cs520": [
        {"slug": "week-1", "title": "Week 1", "url": None},
        {"slug": "week-2", "title": "Week 2", "url": None},
        {"slug": "week-3", "title": "Week 3", "url": None},
    ],
    "https://stanford-cs336.github.io/spring2025": [
        {"slug": "data", "title": "Data", "url": None},
        {"slug": "tokenizer", "title": "Tokenizer", "url": None},
        {"slug": "train", "title": "Train", "url": None},
        {"slug": "eval", "title": "Eval", "url": None},
    ],
    "https://huggingface.co/learn/deep-rl-course/en/unit0/introduction": [
        {"slug": "unit-1", "title": "Unit 1", "url": "https://huggingface.co/learn/deep-rl-course/en/unit1/introduction"},
        {"slug": "unit-2", "title": "Unit 2", "url": "https://huggingface.co/learn/deep-rl-course/en/unit2/introduction"},
        {"slug": "unit-3", "title": "Unit 3", "url": "https://huggingface.co/learn/deep-rl-course/en/unit3/introduction"},
    ],
    "https://www.youtube.com/playlist?list=PLqYmG7hTraZDM-OYHWgPebj2MfCFzFObQ": [
        {"slug": "lec-1", "title": "Lecture 1: Introduction", "url": None},
        {"slug": "lec-2", "title": "Lecture 2: MDPs", "url": None},
        {"slug": "lec-3", "title": "Lecture 3: Planning by dynamic programming", "url": None},
        {"slug": "lec-4", "title": "Lecture 4: Model-free prediction", "url": None},
        {"slug": "lec-5", "title": "Lecture 5: Model-free control", "url": None},
    ],
    "https://nlp.stanford.edu/IR-book": [
        {"slug": "ch1", "title": "Boolean retrieval", "url": None},
        {"slug": "ch6", "title": "Scoring and term weighting", "url": None},
        {"slug": "ch8", "title": "Evaluation in information retrieval", "url": None},
        {"slug": "ch21", "title": "Web search", "url": None},
    ],
    "https://github.com/fastai/numerical-linear-algebra": [
        {"slug": "nb1", "title": "Notebook 1: Why are we here", "url": None},
        {"slug": "nb2", "title": "Notebook 2: Background removal", "url": None},
        {"slug": "nb3", "title": "Notebook 3: Compressed sensing", "url": None},
    ],
}
